version: '3.8'

services:
  SchoolBusApp:
    image: ${DOCKER_REGISTRY-}blazorserver
    build:
      context: .
      dockerfile: src/Blazor.Server.UI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseInMemoryDatabase=true
      - DatabaseSettings__DBProvider=postgresql
      - DatabaseSettings__ConnectionString=Server=postgresdb;Database=schoolbusdb;User Id=root;Password=3#uKC!;Port=5432
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=Password@123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Blazor.Server.UI.pfx
    volumes:
     - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets:ro
     - ~/.aspnet/https:/root/.aspnet/https:ro
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - postgresdb
    restart: on-failure

  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: demo
    volumes:
      - postgres16_data:/var/lib/postgresql/data
volumes:
  postgres16_data:
